client
dev tun
proto udp

remote 10.1.2.2 1194

ca /root/openvpn/keys/ca.crt
cert /root/openvpn/keys/CE1.crt
key /root/openvpn/keys/CE1.key

remote-cert-tls server
persist-key
persist-tun
verb 3
cipher AES-256-GCM