b1  Cleartext-Password := "b1Password"
    Service-Type = Framed-User,
    Tunnel-Type = 13,
    Tunnel-Medium-Type = 6,
    Tunnel-Private-Group-Id = "10",
    Calling-Station-Id = "%{Calling-Station-Id}"


b2  Cleartext-Password := "b2Password"
    Service-Type = Framed-User,
    Tunnel-Type = 13,
    Tunnel-Medium-Type = 6,
    Tunnel-Private-Group-Id = "20",
    Calling-Station-Id = "%{Calling-Station-Id}"
